name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
